# Generated by Django 5.2 on 2025-05-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0002_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="test_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="test",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
